services:
  vpn:
    build:
      dockerfile_inline: |
        FROM alpine
        RUN apk add --no-cache openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./release_arena_us-release-2.ovpn:/vpn/config.ovpn:ro
    command: ["openvpn", "--config", "/vpn/config.ovpn", "--pull-filter", "ignore", "ifconfig-ipv6", "--pull-filter", "ignore", "route-ipv6", "--pull-filter", "ignore", "tun-ipv6"]
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  kali:
    build: .
    entrypoint: ["sleep", "infinity"]
    cap_add:
      - NET_RAW
      - NET_ADMIN
    security_opt:
      - seccomp=unconfined
    network_mode: "service:vpn"
    volumes:
      - .:/htb
      - ptb-home:/home/hacker
    env_file: .env
    environment:
      - TERM=xterm-256color
    stdin_open: true
    tty: true
    depends_on:
      - vpn

volumes:
  ptb-home:
